### ISSUE TITLE
Cannot connect to some servers

### ISSUE THREAD

**Issue by ForNeVeR** [vitalyster/SharpXMPP#15]
For example, I'm trying to connect as `yog-sothoth@codingteam.org.ru`, and it unfortunately tells me:

```
System.ArgumentException: None of the discovered or specified addresses match the socket address family.
Parameter name: addresses
   at System.Net.Sockets.Socket.BeginConnect(IPAddress[] addresses, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.BeginConnect(IPAddress[] addresses, Int32 port, AsyncCallback requestCallback, Object state)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsyncCore>b__64_0(IPAddress[] targetAddresses, Int32 targetPort, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Sockets.TcpClient.ConnectAsyncCore(IPAddress[] addresses, Int32 port)
   at SharpXMPP.XmppTcpConnection.<Connect>d__15.MoveNext()
```

**Comment by ForNeVeR** [comment]
Thanks a lot! I've finally verified that the issue is fixed.
